<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\data\configs\default\Resources\formulas\math_formulas.json" CopyToOutputDirectory="PreserveNewest" Link="MathFormulas.json" />
  </ItemGroup>

</Project>
